//
//  PersistentHistoryCleaner.swift
//  ProdApp
//
//  Created by Ivan Sanna on 01/10/24.
//

import SwiftUI
import CoreData
import Foundation

/// Deletes processed transactions
public struct PersistentHistoryCleaner {
    /// NSPersistentCloudkitContainer
    let container: NSPersistentContainer
    /// app group userDefaults
    let userDefault = UserDefaultsManager.shared.userDefault
    /// all appActors
    let appActors = AppActor.allCases
    
    /// Cleans up processed persistent history transactions
    public func clean() {
        guard let timestamp = userDefault?.lastCommonTransactionTimestamp(in: appActors) else {
            return
        }
        
        // Get the request for deletable transactions
        let deleteHistoryRequest = NSPersistentHistoryChangeRequest.deleteHistory(before: timestamp)
        
        // Only delete Transactions generated by members of the App Group
        if let fetchRequest = NSPersistentHistoryTransaction.fetchRequest {
            var predicates: [NSPredicate] = []
            
            appActors.forEach { appActor in
                // Clean up Transactions created by App Group members
                let predicate = NSPredicate(format: "%K = %@",
                                            #keyPath(NSPersistentHistoryTransaction.author),
                                            appActor.rawValue)
                predicates.append(predicate)
            }
            
            let compoundPredicate = NSCompoundPredicate(type: .or, subpredicates: predicates)
            fetchRequest.predicate = compoundPredicate
            deleteHistoryRequest.fetchRequest = fetchRequest
        }
        
        container.performBackgroundTask { context in
            do {
                try context.execute(deleteHistoryRequest)
                // Reset the timestamp for all appActors
                appActors.forEach { actor in
                    userDefault?.updateLastHistoryTransactionTimestamp(for: actor, to: nil)
                }
            } catch {
                print(error)
            }
        }
    }
}
