//
//  PersistentHistoryTrackingHelper.swift
//  ProdApp
//
//  Created by Ivan Sanna on 01/10/24.
//

import Combine
import CoreData
import Foundation

enum AppActor: String, CaseIterable {
    case mainApp  // iOS App
    case monitorExtension // Device Activity Monitor Extension
}

final class PersistentHistoryTrackingHelper {
    init(container: NSPersistentContainer, currentActor: AppActor) {
        self.container = container
        self.currentActor = currentActor
        
        // Register to respond to StoreRemoteChange
        NotificationCenter.default.publisher(
            for: .NSPersistentStoreRemoteChange,
            object: container.persistentStoreCoordinator
        )
        .subscribe(on: queue, options: nil)
        .sink { _ in
            // The content of the notification is meaningless, it simply serves as a signal that something needs to be processed
            self.processor()
        }
        .store(in: &cancellables)
    }
    
    var container: NSPersistentContainer
    var currentActor: AppActor
    let userDefaults = UserDefaultsManager.shared.userDefault
    
    lazy var backgroundContext = { container.newBackgroundContext() }()
    
    private var cancellables: Set<AnyCancellable> = []
    private lazy var queue = {
        DispatchQueue(label: "com.ivansanna.\(self.currentActor.rawValue).processPersistentHistory")
    }()
    
    /// Process persistent history
    private func processor() {
        // Operate in the correct context to avoid affecting the main thread
        backgroundContext.performAndWait {
            // fetcher is used to obtain transactions that need processing
            guard let transactions = try? fetcher() else { return }
            // merger merges the transactions into the current view context
            merger(transaction: transactions)
        }
    }
    
    enum Error: String, Swift.Error {
        case historyTransactionConvertionFailed
    }
    // Get filtered Transactions
    func fetcher() throws -> [NSPersistentHistoryTransaction] {
        let fromDate = userDefaults?.lastHistoryTransactionTimestamp(for: currentActor) ?? Date.distantPast
        NSPersistentHistoryChangeRequest.fetchHistory(after: fromDate)
        
        let historyFetchRequest = NSPersistentHistoryChangeRequest.fetchHistory(after: fromDate)
        if let fetchRequest = NSPersistentHistoryTransaction.fetchRequest {
            var predicates: [NSPredicate] = []
            
            AppActor.allCases.forEach { appActor in
                if appActor == currentActor {
                    // This code assumes that in the App, even operations performed through backgroud have been immediately merged into ViewContext
                    // Therefore, for the current appActor, only process transactions generated by the batchContext context
                    let predicate = NSPredicate(format: "%K = %@ AND %K = %@",
                                                #keyPath(NSPersistentHistoryTransaction.author),
                                                appActor.rawValue,
                                                #keyPath(NSPersistentHistoryTransaction.contextName),
                                                "batchContext")
                    predicates.append(predicate)
                } else {
                    // For transactions generated by other appActors, all need to be processed
                    let predicate = NSPredicate(format: "%K = %@",
                                                #keyPath(NSPersistentHistoryTransaction.author),
                                                appActor.rawValue)
                    predicates.append(predicate)
                }
            }
            
            let compoundPredicate = NSCompoundPredicate(type: .or, subpredicates: predicates)
            fetchRequest.predicate = compoundPredicate
            historyFetchRequest.fetchRequest = fetchRequest
        }
        guard let historyResult = try backgroundContext.execute(historyFetchRequest) as? NSPersistentHistoryResult,
              let history = historyResult.result as? [NSPersistentHistoryTransaction]
        else {
            throw Error.historyTransactionConvertionFailed
        }
        return history
    }
    
    func merger(transaction: [NSPersistentHistoryTransaction]) {
        let viewContext = container.viewContext
        viewContext.perform {
            transaction.forEach { transaction in
                let userInfo = transaction.objectIDNotification().userInfo ?? [:]
                NSManagedObjectContext.mergeChanges(fromRemoteContextSave: userInfo, into: [viewContext])
            }
        }
        
        // Update the last transaction timestamp
        guard let lastTimestamp = transaction.last?.timestamp else { return }
        userDefaults?.updateLastHistoryTransactionTimestamp(for: currentActor, to: lastTimestamp)
    }
    
}
